In [31]:
import numpy as np
import pandas as pd

In [32]:
df = pd.read_csv('bhavdata.csv') #Reading the CSV
df

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.10,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.00,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
3,FUTIDX,NIFTY,27-Aug-2020,0.0,XX,11274.95,11334.75,11242.05,11293.35,11293.35,125516,1063750.23,10313625,-35325,10-AUG-2020,NaN
4,FUTIDX,NIFTY,24-Sep-2020,0.0,XX,11262.00,11339.10,11252.95,11301.45,11301.45,6244,52947.72,948825,32175,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34845,OPTSTK,ZEEL,29-Oct-2020,190.0,PE,0.00,0.00,0.00,58.40,45.40,0,0.00,0,0,10-AUG-2020,NaN
34846,OPTSTK,ZEEL,29-Oct-2020,195.0,PE,0.00,0.00,0.00,62.45,49.40,0,0.00,0,0,10-AUG-2020,NaN
34847,OPTSTK,ZEEL,29-Oct-2020,200.0,PE,0.00,0.00,0.00,66.60,53.50,0,0.00,0,0,10-AUG-2020,NaN
34848,OPTSTK,ZEEL,29-Oct-2020,205.0,PE,0.00,0.00,0.00,70.80,57.70,0,0.00,0,0,10-AUG-2020,NaN
34849,OPTSTK,ZEEL,29-Oct-2020,210.0,PE,0.00,0.00,0.00,75.05,61.95,0,0.00,0,0,10-AUG-2020,NaN

In [33]:
df.shape # Tells the Number of Rows and Columns present in the whole CSV File

(34850, 16)

In [34]:
df1 = df[df['INSTRUMENT'].str.contains('OPTIDX')] #Filtering only OPT from the whole Instruments
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
417,OPTIDX,BANKNIFTY,13-Aug-2020,16900.0,CE,5200.7,5200.7,5038.35,5038.35,5006.15,2,11.0,0,0,10-AUG-2020,NaN
418,OPTIDX,BANKNIFTY,13-Aug-2020,17000.0,CE,0.0,0.0,0.00,3432.50,4906.20,0,0.0,0,0,10-AUG-2020,NaN
419,OPTIDX,BANKNIFTY,13-Aug-2020,17100.0,CE,0.0,0.0,0.00,3356.00,4806.20,0,0.0,0,0,10-AUG-2020,NaN
420,OPTIDX,BANKNIFTY,13-Aug-2020,17200.0,CE,0.0,0.0,0.00,3280.45,4706.25,0,0.0,0,0,10-AUG-2020,NaN
421,OPTIDX,BANKNIFTY,13-Aug-2020,17300.0,CE,0.0,0.0,0.00,3205.80,4606.30,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.00,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.00,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.00,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.00,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.00,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [35]:
# Define all the symbols that you want the OPTINX and OPTSTK for in the multisymbols, in the same format
#Filtering all the symbols to a new dataframe
multisymbols = ['NIFTY']
df1 = df1[df['SYMBOL'].isin(multisymbols)]
df1

<ipython-input-35-f921a6e793f3>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['SYMBOL'].isin(multisymbols)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2039,OPTIDX,NIFTY,13-Aug-2020,8300.0,CE,0.0,0.0,0.0,1654.05,2973.05,0,0.0,0,0,10-AUG-2020,NaN
2040,OPTIDX,NIFTY,13-Aug-2020,8350.0,CE,0.0,0.0,0.0,1611.25,2923.05,0,0.0,0,0,10-AUG-2020,NaN
2041,OPTIDX,NIFTY,13-Aug-2020,8400.0,CE,0.0,0.0,0.0,1660.85,2873.10,0,0.0,0,0,10-AUG-2020,NaN
2042,OPTIDX,NIFTY,13-Aug-2020,8450.0,CE,0.0,0.0,0.0,1618.75,2823.10,0,0.0,0,0,10-AUG-2020,NaN
2043,OPTIDX,NIFTY,13-Aug-2020,8500.0,CE,0.0,0.0,0.0,1577.05,2773.10,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.0,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.0,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.0,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.0,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.0,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [36]:
#Change according to liking
#Get a single date or a specific date
dates = ["27-Aug-2020"] 
df1 = df1[df['EXPIRY_DT'].isin(dates)]
df1

<ipython-input-36-6674059c3095>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['EXPIRY_DT'].isin(dates)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2391,OPTIDX,NIFTY,27-Aug-2020,8000.0,CE,3293.95,3329.05,3261.30,3289.85,3289.85,313,2653.33,212475,-20100,10-AUG-2020,NaN
2392,OPTIDX,NIFTY,27-Aug-2020,8050.0,CE,0.00,0.00,0.00,1833.90,3236.05,0,0.00,0,0,10-AUG-2020,NaN
2393,OPTIDX,NIFTY,27-Aug-2020,8100.0,CE,0.00,0.00,0.00,1798.30,3186.15,0,0.00,0,0,10-AUG-2020,NaN
2394,OPTIDX,NIFTY,27-Aug-2020,8150.0,CE,0.00,0.00,0.00,1763.15,3136.25,0,0.00,0,0,10-AUG-2020,NaN
2395,OPTIDX,NIFTY,27-Aug-2020,8200.0,CE,0.00,0.00,0.00,1728.40,3086.35,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,OPTIDX,NIFTY,27-Aug-2020,12600.0,PE,1336.35,1336.35,1336.35,1336.35,1316.90,1,10.45,3300,75,10-AUG-2020,NaN
2581,OPTIDX,NIFTY,27-Aug-2020,12650.0,PE,0.00,0.00,0.00,1524.40,1365.10,0,0.00,0,0,10-AUG-2020,NaN
2582,OPTIDX,NIFTY,27-Aug-2020,12700.0,PE,1386.60,1430.60,1386.60,1430.60,1413.50,3,31.73,10500,-225,10-AUG-2020,NaN
2583,OPTIDX,NIFTY,27-Aug-2020,12750.0,PE,0.00,0.00,0.00,1476.55,1462.10,0,0.00,0,0,10-AUG-2020,NaN
2584,OPTIDX,NIFTY,27-Aug-2020,12800.0,PE,1507.00,1507.00,1472.45,1499.95,1499.95,11,117.84,8775,450,10-AUG-2020,NaN

In [37]:
#Filters out all the Values of only PE
df1 = df1[df['OPTION_TYP'].str.contains("PE")]
df1

<ipython-input-37-2e1b86d2d782>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['OPTION_TYP'].str.contains("PE")]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2488,OPTIDX,NIFTY,27-Aug-2020,8000.0,PE,2.40,2.50,2.05,2.15,2.15,1947,11685.36,738075,-21075,10-AUG-2020,NaN
2489,OPTIDX,NIFTY,27-Aug-2020,8050.0,PE,0.00,0.00,0.00,296.05,0.05,0,0.00,0,0,10-AUG-2020,NaN
2490,OPTIDX,NIFTY,27-Aug-2020,8100.0,PE,2.45,2.70,2.20,2.30,2.30,158,960.14,23100,2700,10-AUG-2020,NaN
2491,OPTIDX,NIFTY,27-Aug-2020,8150.0,PE,0.00,0.00,0.00,324.10,0.05,0,0.00,0,0,10-AUG-2020,NaN
2492,OPTIDX,NIFTY,27-Aug-2020,8200.0,PE,2.10,2.80,2.05,2.40,2.40,61,375.26,14925,-150,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,OPTIDX,NIFTY,27-Aug-2020,12600.0,PE,1336.35,1336.35,1336.35,1336.35,1316.90,1,10.45,3300,75,10-AUG-2020,NaN
2581,OPTIDX,NIFTY,27-Aug-2020,12650.0,PE,0.00,0.00,0.00,1524.40,1365.10,0,0.00,0,0,10-AUG-2020,NaN
2582,OPTIDX,NIFTY,27-Aug-2020,12700.0,PE,1386.60,1430.60,1386.60,1430.60,1413.50,3,31.73,10500,-225,10-AUG-2020,NaN
2583,OPTIDX,NIFTY,27-Aug-2020,12750.0,PE,0.00,0.00,0.00,1476.55,1462.10,0,0.00,0,0,10-AUG-2020,NaN
2584,OPTIDX,NIFTY,27-Aug-2020,12800.0,PE,1507.00,1507.00,1472.45,1499.95,1499.95,11,117.84,8775,450,10-AUG-2020,NaN

In [38]:
df1 = df1.sort_values(['CHG_IN_OI'], ascending=False)
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2554,OPTIDX,NIFTY,27-Aug-2020,11300.0,PE,215.55,223.10,179.00,192.05,192.05,30526,263130.83,639450,191625,10-AUG-2020,NaN
2552,OPTIDX,NIFTY,27-Aug-2020,11200.0,PE,150.00,176.25,140.20,149.70,149.70,28751,244780.69,1368600,105525,10-AUG-2020,NaN
2546,OPTIDX,NIFTY,27-Aug-2020,10900.0,PE,63.05,78.75,62.00,66.65,66.65,17800,146423.15,961725,76875,10-AUG-2020,NaN
2543,OPTIDX,NIFTY,27-Aug-2020,10750.0,PE,46.65,52.85,40.30,42.85,42.85,1655,13398.92,73350,28650,10-AUG-2020,NaN
2551,OPTIDX,NIFTY,27-Aug-2020,11150.0,PE,140.05,153.75,124.05,131.30,131.30,1414,11965.32,56325,23550,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548,OPTIDX,NIFTY,27-Aug-2020,11000.0,PE,104.50,105.10,82.50,88.30,88.30,47960,398922.20,2991225,-71850,10-AUG-2020,NaN
2542,OPTIDX,NIFTY,27-Aug-2020,10700.0,PE,42.50,46.45,34.70,37.05,37.05,12527,100893.77,1015950,-75750,10-AUG-2020,NaN
2550,OPTIDX,NIFTY,27-Aug-2020,11100.0,PE,138.85,138.95,108.55,115.85,115.85,24818,208811.13,1215300,-79800,10-AUG-2020,NaN
2532,OPTIDX,NIFTY,27-Aug-2020,10200.0,PE,10.55,13.35,9.45,9.75,9.75,6984,53483.35,729600,-87450,10-AUG-2020,NaN
2568,OPTIDX,NIFTY,27-Aug-2020,12000.0,PE,733.00,760.50,681.55,720.95,720.95,4094,39011.39,435600,-124575,10-AUG-2020,NaN

In [40]:
df1 = df1.iloc[:1]
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2554,OPTIDX,NIFTY,27-Aug-2020,11300.0,PE,215.55,223.1,179.0,192.05,192.05,30526,263130.83,639450,191625,10-AUG-2020,NaN

In [41]:
df1.to_csv('OPTIDX_PE_Nifty.csv')

In [43]:
DF = pd.read_csv("bhavdata.csv")
DF

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.10,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.00,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
3,FUTIDX,NIFTY,27-Aug-2020,0.0,XX,11274.95,11334.75,11242.05,11293.35,11293.35,125516,1063750.23,10313625,-35325,10-AUG-2020,NaN
4,FUTIDX,NIFTY,24-Sep-2020,0.0,XX,11262.00,11339.10,11252.95,11301.45,11301.45,6244,52947.72,948825,32175,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34845,OPTSTK,ZEEL,29-Oct-2020,190.0,PE,0.00,0.00,0.00,58.40,45.40,0,0.00,0,0,10-AUG-2020,NaN
34846,OPTSTK,ZEEL,29-Oct-2020,195.0,PE,0.00,0.00,0.00,62.45,49.40,0,0.00,0,0,10-AUG-2020,NaN
34847,OPTSTK,ZEEL,29-Oct-2020,200.0,PE,0.00,0.00,0.00,66.60,53.50,0,0.00,0,0,10-AUG-2020,NaN
34848,OPTSTK,ZEEL,29-Oct-2020,205.0,PE,0.00,0.00,0.00,70.80,57.70,0,0.00,0,0,10-AUG-2020,NaN
34849,OPTSTK,ZEEL,29-Oct-2020,210.0,PE,0.00,0.00,0.00,75.05,61.95,0,0.00,0,0,10-AUG-2020,NaN

In [45]:
df2 = DF[df['INSTUMENT'].str.contains('OPTIDX')]
df2

KeyError: 'INSTUMENT'

In [ ]:
multsym = ['BANKNIFTY']
df2 = DF[df['SYMBOL'].isin(multsym)]
df2

In [ ]:
df2 = df2[df['EXPIRY_DT'].isin(dates)]
df2

In [ ]:
#Filters out all the Values of only PE
df2 = df2[df['OPTION_TYP'].str.contains('PE')]
df2

In [ ]:
df2 = df2.sort_values(['CHG_IN_OI'], ascending=False)
df2

In [ ]:
df2 = df2.iloc[:1]

In [ ]:
df2.to_csv('OPTIDX_PE_Banknifty.csv')