In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('bhavdata.csv') #Reading the CSV
df

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.10,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.00,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
3,FUTIDX,NIFTY,27-Aug-2020,0.0,XX,11274.95,11334.75,11242.05,11293.35,11293.35,125516,1063750.23,10313625,-35325,10-AUG-2020,NaN
4,FUTIDX,NIFTY,24-Sep-2020,0.0,XX,11262.00,11339.10,11252.95,11301.45,11301.45,6244,52947.72,948825,32175,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34845,OPTSTK,ZEEL,29-Oct-2020,190.0,PE,0.00,0.00,0.00,58.40,45.40,0,0.00,0,0,10-AUG-2020,NaN
34846,OPTSTK,ZEEL,29-Oct-2020,195.0,PE,0.00,0.00,0.00,62.45,49.40,0,0.00,0,0,10-AUG-2020,NaN
34847,OPTSTK,ZEEL,29-Oct-2020,200.0,PE,0.00,0.00,0.00,66.60,53.50,0,0.00,0,0,10-AUG-2020,NaN
34848,OPTSTK,ZEEL,29-Oct-2020,205.0,PE,0.00,0.00,0.00,70.80,57.70,0,0.00,0,0,10-AUG-2020,NaN
34849,OPTSTK,ZEEL,29-Oct-2020,210.0,PE,0.00,0.00,0.00,75.05,61.95,0,0.00,0,0,10-AUG-2020,NaN

In [3]:
df.shape # Tells the Number of Rows and Columns present in the whole CSV File

(34850, 16)

In [4]:
df1 = df[df['INSTRUMENT'].str.contains('OPTIDX')] #Filtering only OPT from the whole Instruments
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
417,OPTIDX,BANKNIFTY,13-Aug-2020,16900.0,CE,5200.7,5200.7,5038.35,5038.35,5006.15,2,11.0,0,0,10-AUG-2020,NaN
418,OPTIDX,BANKNIFTY,13-Aug-2020,17000.0,CE,0.0,0.0,0.00,3432.50,4906.20,0,0.0,0,0,10-AUG-2020,NaN
419,OPTIDX,BANKNIFTY,13-Aug-2020,17100.0,CE,0.0,0.0,0.00,3356.00,4806.20,0,0.0,0,0,10-AUG-2020,NaN
420,OPTIDX,BANKNIFTY,13-Aug-2020,17200.0,CE,0.0,0.0,0.00,3280.45,4706.25,0,0.0,0,0,10-AUG-2020,NaN
421,OPTIDX,BANKNIFTY,13-Aug-2020,17300.0,CE,0.0,0.0,0.00,3205.80,4606.30,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.00,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.00,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.00,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.00,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.00,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [5]:
# Define all the symbols that you want the OPTINX and OPTSTK for in the multisymbols, in the same format
#Filtering all the symbols to a new dataframe
multisymbols = ['NIFTY']
df1 = df1[df['SYMBOL'].isin(multisymbols)]
df1

<ipython-input-5-f921a6e793f3>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['SYMBOL'].isin(multisymbols)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2039,OPTIDX,NIFTY,13-Aug-2020,8300.0,CE,0.0,0.0,0.0,1654.05,2973.05,0,0.0,0,0,10-AUG-2020,NaN
2040,OPTIDX,NIFTY,13-Aug-2020,8350.0,CE,0.0,0.0,0.0,1611.25,2923.05,0,0.0,0,0,10-AUG-2020,NaN
2041,OPTIDX,NIFTY,13-Aug-2020,8400.0,CE,0.0,0.0,0.0,1660.85,2873.10,0,0.0,0,0,10-AUG-2020,NaN
2042,OPTIDX,NIFTY,13-Aug-2020,8450.0,CE,0.0,0.0,0.0,1618.75,2823.10,0,0.0,0,0,10-AUG-2020,NaN
2043,OPTIDX,NIFTY,13-Aug-2020,8500.0,CE,0.0,0.0,0.0,1577.05,2773.10,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.0,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.0,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.0,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.0,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.0,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [6]:
#Change according to liking
#Get a single date or a specific date
dates = ["27-Aug-2020"] 
df1 = df1[df['EXPIRY_DT'].isin(dates)]
df1

<ipython-input-6-6674059c3095>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['EXPIRY_DT'].isin(dates)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2391,OPTIDX,NIFTY,27-Aug-2020,8000.0,CE,3293.95,3329.05,3261.30,3289.85,3289.85,313,2653.33,212475,-20100,10-AUG-2020,NaN
2392,OPTIDX,NIFTY,27-Aug-2020,8050.0,CE,0.00,0.00,0.00,1833.90,3236.05,0,0.00,0,0,10-AUG-2020,NaN
2393,OPTIDX,NIFTY,27-Aug-2020,8100.0,CE,0.00,0.00,0.00,1798.30,3186.15,0,0.00,0,0,10-AUG-2020,NaN
2394,OPTIDX,NIFTY,27-Aug-2020,8150.0,CE,0.00,0.00,0.00,1763.15,3136.25,0,0.00,0,0,10-AUG-2020,NaN
2395,OPTIDX,NIFTY,27-Aug-2020,8200.0,CE,0.00,0.00,0.00,1728.40,3086.35,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,OPTIDX,NIFTY,27-Aug-2020,12600.0,PE,1336.35,1336.35,1336.35,1336.35,1316.90,1,10.45,3300,75,10-AUG-2020,NaN
2581,OPTIDX,NIFTY,27-Aug-2020,12650.0,PE,0.00,0.00,0.00,1524.40,1365.10,0,0.00,0,0,10-AUG-2020,NaN
2582,OPTIDX,NIFTY,27-Aug-2020,12700.0,PE,1386.60,1430.60,1386.60,1430.60,1413.50,3,31.73,10500,-225,10-AUG-2020,NaN
2583,OPTIDX,NIFTY,27-Aug-2020,12750.0,PE,0.00,0.00,0.00,1476.55,1462.10,0,0.00,0,0,10-AUG-2020,NaN
2584,OPTIDX,NIFTY,27-Aug-2020,12800.0,PE,1507.00,1507.00,1472.45,1499.95,1499.95,11,117.84,8775,450,10-AUG-2020,NaN

In [7]:
#Filters out all the Values of only CE
df1 = df1[df['OPTION_TYP'].str.contains("CE")]
df1

<ipython-input-7-2f5de76fd862>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['OPTION_TYP'].str.contains("CE")]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2391,OPTIDX,NIFTY,27-Aug-2020,8000.0,CE,3293.95,3329.05,3261.30,3289.85,3289.85,313,2653.33,212475,-20100,10-AUG-2020,NaN
2392,OPTIDX,NIFTY,27-Aug-2020,8050.0,CE,0.00,0.00,0.00,1833.90,3236.05,0,0.00,0,0,10-AUG-2020,NaN
2393,OPTIDX,NIFTY,27-Aug-2020,8100.0,CE,0.00,0.00,0.00,1798.30,3186.15,0,0.00,0,0,10-AUG-2020,NaN
2394,OPTIDX,NIFTY,27-Aug-2020,8150.0,CE,0.00,0.00,0.00,1763.15,3136.25,0,0.00,0,0,10-AUG-2020,NaN
2395,OPTIDX,NIFTY,27-Aug-2020,8200.0,CE,0.00,0.00,0.00,1728.40,3086.35,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2483,OPTIDX,NIFTY,27-Aug-2020,12600.0,CE,3.65,3.65,3.05,3.40,3.40,611,5775.48,124125,-7875,10-AUG-2020,NaN
2484,OPTIDX,NIFTY,27-Aug-2020,12650.0,CE,3.40,3.45,3.05,3.45,3.45,43,408.06,2325,-825,10-AUG-2020,NaN
2485,OPTIDX,NIFTY,27-Aug-2020,12700.0,CE,2.60,3.50,2.60,3.30,3.30,320,3048.73,131700,-3975,10-AUG-2020,NaN
2486,OPTIDX,NIFTY,27-Aug-2020,12750.0,CE,3.35,3.80,2.25,2.65,7.45,24,229.55,2850,150,10-AUG-2020,NaN
2487,OPTIDX,NIFTY,27-Aug-2020,12800.0,CE,4.65,5.40,2.25,2.80,2.80,850,8161.70,100275,1875,10-AUG-2020,NaN

In [8]:
df1 = df1.sort_values(['CHG_IN_OI'], ascending=False)
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2463,OPTIDX,NIFTY,27-Aug-2020,11600.0,CE,71.80,81.20,58.35,67.30,67.30,20059,175603.60,751350,80325,10-AUG-2020,NaN
2457,OPTIDX,NIFTY,27-Aug-2020,11300.0,CE,174.20,214.40,163.90,186.40,186.40,37109,319975.92,1143450,46275,10-AUG-2020,NaN
2473,OPTIDX,NIFTY,27-Aug-2020,12100.0,CE,8.10,12.20,8.05,10.00,10.00,3647,33126.19,309300,35025,10-AUG-2020,NaN
2464,OPTIDX,NIFTY,27-Aug-2020,11650.0,CE,59.50,67.10,45.00,55.50,55.50,1877,16486.20,72375,32325,10-AUG-2020,NaN
2465,OPTIDX,NIFTY,27-Aug-2020,11700.0,CE,42.45,54.65,39.20,45.10,45.10,18098,159472.49,680325,26850,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2461,OPTIDX,NIFTY,27-Aug-2020,11500.0,CE,96.15,116.30,85.10,98.25,98.25,42081,366262.01,2103225,-100875,10-AUG-2020,NaN
2459,OPTIDX,NIFTY,27-Aug-2020,11400.0,CE,137.90,161.60,120.30,138.00,138.00,22990,199107.56,638775,-106875,10-AUG-2020,NaN
2411,OPTIDX,NIFTY,27-Aug-2020,9000.0,CE,2270.00,2333.20,2244.05,2293.75,2293.75,3062,25982.69,422400,-110400,10-AUG-2020,NaN
2455,OPTIDX,NIFTY,27-Aug-2020,11200.0,CE,211.65,275.20,207.05,243.55,243.55,20699,177815.56,973050,-112725,10-AUG-2020,NaN
2451,OPTIDX,NIFTY,27-Aug-2020,11000.0,CE,355.00,418.00,348.00,381.40,381.40,6958,59448.78,951225,-122100,10-AUG-2020,NaN

In [9]:
df1 = df1.iloc[:1]
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2463,OPTIDX,NIFTY,27-Aug-2020,11600.0,CE,71.8,81.2,58.35,67.3,67.3,20059,175603.6,751350,80325,10-AUG-2020,NaN

In [10]:
df1.to_csv('OPTIDX_CE_Nifty.csv')

In [11]:
DF = pd.read_csv('bhavdata.csv')
DF

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.10,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.00,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
3,FUTIDX,NIFTY,27-Aug-2020,0.0,XX,11274.95,11334.75,11242.05,11293.35,11293.35,125516,1063750.23,10313625,-35325,10-AUG-2020,NaN
4,FUTIDX,NIFTY,24-Sep-2020,0.0,XX,11262.00,11339.10,11252.95,11301.45,11301.45,6244,52947.72,948825,32175,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34845,OPTSTK,ZEEL,29-Oct-2020,190.0,PE,0.00,0.00,0.00,58.40,45.40,0,0.00,0,0,10-AUG-2020,NaN
34846,OPTSTK,ZEEL,29-Oct-2020,195.0,PE,0.00,0.00,0.00,62.45,49.40,0,0.00,0,0,10-AUG-2020,NaN
34847,OPTSTK,ZEEL,29-Oct-2020,200.0,PE,0.00,0.00,0.00,66.60,53.50,0,0.00,0,0,10-AUG-2020,NaN
34848,OPTSTK,ZEEL,29-Oct-2020,205.0,PE,0.00,0.00,0.00,70.80,57.70,0,0.00,0,0,10-AUG-2020,NaN
34849,OPTSTK,ZEEL,29-Oct-2020,210.0,PE,0.00,0.00,0.00,75.05,61.95,0,0.00,0,0,10-AUG-2020,NaN

In [12]:
multsym = ['BANKNIFTY']
df2 = DF[df['SYMBOL'].isin(multsym)]
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.0,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.1,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.0,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
417,OPTIDX,BANKNIFTY,13-Aug-2020,16900.0,CE,5200.70,5200.7,5038.35,5038.35,5006.15,2,11.00,0,0,10-AUG-2020,NaN
418,OPTIDX,BANKNIFTY,13-Aug-2020,17000.0,CE,0.00,0.0,0.00,3432.50,4906.20,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034,OPTIDX,BANKNIFTY,29-Oct-2020,24400.0,PE,0.00,0.0,0.00,3587.00,3051.40,0,0.00,0,0,10-AUG-2020,NaN
2035,OPTIDX,BANKNIFTY,29-Oct-2020,24500.0,PE,0.00,0.0,0.00,3658.40,3124.70,0,0.00,0,0,10-AUG-2020,NaN
2036,OPTIDX,BANKNIFTY,29-Oct-2020,24600.0,PE,0.00,0.0,0.00,3730.35,3198.75,0,0.00,0,0,10-AUG-2020,NaN
2037,OPTIDX,BANKNIFTY,29-Oct-2020,24700.0,PE,0.00,0.0,0.00,3636.65,3273.45,0,0.00,0,0,10-AUG-2020,NaN
2038,OPTIDX,BANKNIFTY,29-Oct-2020,24800.0,PE,0.00,0.0,0.00,3710.20,3348.90,0,0.00,0,0,10-AUG-2020,NaN

In [13]:
df2 = df2[df['EXPIRY_DT'].isin(dates)]
df2

<ipython-input-13-9aa28cb238d1>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df['EXPIRY_DT'].isin(dates)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
767,OPTIDX,BANKNIFTY,27-Aug-2020,16200.0,CE,0.00,0.00,0.00,5200.00,5732.35,0,0.00,25,0,10-AUG-2020,NaN
768,OPTIDX,BANKNIFTY,27-Aug-2020,16300.0,CE,0.00,0.00,0.00,4431.95,5632.55,0,0.00,0,0,10-AUG-2020,NaN
769,OPTIDX,BANKNIFTY,27-Aug-2020,16400.0,CE,0.00,0.00,0.00,4372.10,5532.80,0,0.00,0,0,10-AUG-2020,NaN
770,OPTIDX,BANKNIFTY,27-Aug-2020,16500.0,CE,5475.15,5580.60,5427.60,5427.60,5433.00,37,203.72,2925,-350,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,OPTIDX,BANKNIFTY,27-Aug-2020,25700.0,PE,0.00,0.00,0.00,3315.45,3772.35,0,0.00,0,0,10-AUG-2020,NaN
963,OPTIDX,BANKNIFTY,27-Aug-2020,25800.0,PE,0.00,0.00,0.00,3391.55,3869.55,0,0.00,0,0,10-AUG-2020,NaN
964,OPTIDX,BANKNIFTY,27-Aug-2020,25900.0,PE,0.00,0.00,0.00,3468.35,3967.00,0,0.00,0,0,10-AUG-2020,NaN
965,OPTIDX,BANKNIFTY,27-Aug-2020,26000.0,PE,4020.00,4069.85,3954.25,4069.85,4064.70,12,89.97,4500,-300,10-AUG-2020,NaN
966,OPTIDX,BANKNIFTY,27-Aug-2020,26100.0,PE,0.00,0.00,0.00,3318.65,4162.65,0,0.00,0,0,10-AUG-2020,NaN

In [14]:
#Filters out all the Values of only CE
df2 = df2[df['OPTION_TYP'].str.contains('CE')]
df2

<ipython-input-14-a5a457abaac3>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df['OPTION_TYP'].str.contains('CE')]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
767,OPTIDX,BANKNIFTY,27-Aug-2020,16200.0,CE,0.00,0.00,0.00,5200.00,5732.35,0,0.00,25,0,10-AUG-2020,NaN
768,OPTIDX,BANKNIFTY,27-Aug-2020,16300.0,CE,0.00,0.00,0.00,4431.95,5632.55,0,0.00,0,0,10-AUG-2020,NaN
769,OPTIDX,BANKNIFTY,27-Aug-2020,16400.0,CE,0.00,0.00,0.00,4372.10,5532.80,0,0.00,0,0,10-AUG-2020,NaN
770,OPTIDX,BANKNIFTY,27-Aug-2020,16500.0,CE,5475.15,5580.60,5427.60,5427.60,5433.00,37,203.72,2925,-350,10-AUG-2020,NaN
771,OPTIDX,BANKNIFTY,27-Aug-2020,16600.0,CE,0.00,0.00,0.00,4254.20,5333.25,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,OPTIDX,BANKNIFTY,27-Aug-2020,25700.0,CE,0.00,0.00,0.00,683.95,23.40,0,0.00,0,0,10-AUG-2020,NaN
863,OPTIDX,BANKNIFTY,27-Aug-2020,25800.0,CE,0.00,0.00,0.00,660.70,20.80,0,0.00,0,0,10-AUG-2020,NaN
864,OPTIDX,BANKNIFTY,27-Aug-2020,25900.0,CE,0.00,0.00,0.00,638.10,18.45,0,0.00,0,0,10-AUG-2020,NaN
865,OPTIDX,BANKNIFTY,27-Aug-2020,26000.0,CE,10.55,13.00,9.45,11.35,11.35,250,1625.70,30000,450,10-AUG-2020,NaN
866,OPTIDX,BANKNIFTY,27-Aug-2020,26100.0,CE,10.00,16.85,9.40,10.40,10.40,97,633.22,1450,550,10-AUG-2020,NaN

In [15]:
df2 = df2.sort_values(['CHG_IN_OI'], ascending=False)
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
830,OPTIDX,BANKNIFTY,27-Aug-2020,22500.0,CE,351.65,452.10,330.00,387.10,387.10,16251,93036.06,296200,23075,10-AUG-2020,NaN
835,OPTIDX,BANKNIFTY,27-Aug-2020,23000.0,CE,202.05,278.20,197.70,232.65,232.65,18509,107547.34,286875,21200,10-AUG-2020,NaN
850,OPTIDX,BANKNIFTY,27-Aug-2020,24500.0,CE,34.60,46.30,29.25,38.25,38.25,4585,28129.57,219950,13250,10-AUG-2020,NaN
840,OPTIDX,BANKNIFTY,27-Aug-2020,23500.0,CE,115.95,159.95,108.75,131.35,131.35,10959,64757.11,144250,11375,10-AUG-2020,NaN
827,OPTIDX,BANKNIFTY,27-Aug-2020,22200.0,CE,440.95,584.20,440.90,504.85,504.85,1714,9738.54,16375,3200,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,OPTIDX,BANKNIFTY,27-Aug-2020,21700.0,CE,748.40,855.30,670.95,759.90,759.90,1048,5892.31,8625,-3700,10-AUG-2020,NaN
845,OPTIDX,BANKNIFTY,27-Aug-2020,24000.0,CE,69.70,88.50,59.70,72.30,72.30,9080,54649.08,192000,-4450,10-AUG-2020,NaN
823,OPTIDX,BANKNIFTY,27-Aug-2020,21800.0,CE,649.95,797.90,615.00,704.20,704.20,2022,11387.30,10525,-4650,10-AUG-2020,NaN
825,OPTIDX,BANKNIFTY,27-Aug-2020,22000.0,CE,578.90,685.00,525.00,599.70,599.70,21009,118805.86,289150,-23350,10-AUG-2020,NaN
820,OPTIDX,BANKNIFTY,27-Aug-2020,21500.0,CE,818.65,985.35,785.00,877.85,877.85,7050,39499.43,91325,-53750,10-AUG-2020,NaN

In [16]:
df2 = df2.iloc[:1]
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
830,OPTIDX,BANKNIFTY,27-Aug-2020,22500.0,CE,351.65,452.1,330.0,387.1,387.1,16251,93036.06,296200,23075,10-AUG-2020,NaN

In [17]:
df2.to_csv('OPTIDX_CE_Banknifty.csv')