In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('bhavdata.csv') #Reading the CSV
df

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.10,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.00,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
3,FUTIDX,NIFTY,27-Aug-2020,0.0,XX,11274.95,11334.75,11242.05,11293.35,11293.35,125516,1063750.23,10313625,-35325,10-AUG-2020,NaN
4,FUTIDX,NIFTY,24-Sep-2020,0.0,XX,11262.00,11339.10,11252.95,11301.45,11301.45,6244,52947.72,948825,32175,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34845,OPTSTK,ZEEL,29-Oct-2020,190.0,PE,0.00,0.00,0.00,58.40,45.40,0,0.00,0,0,10-AUG-2020,NaN
34846,OPTSTK,ZEEL,29-Oct-2020,195.0,PE,0.00,0.00,0.00,62.45,49.40,0,0.00,0,0,10-AUG-2020,NaN
34847,OPTSTK,ZEEL,29-Oct-2020,200.0,PE,0.00,0.00,0.00,66.60,53.50,0,0.00,0,0,10-AUG-2020,NaN
34848,OPTSTK,ZEEL,29-Oct-2020,205.0,PE,0.00,0.00,0.00,70.80,57.70,0,0.00,0,0,10-AUG-2020,NaN
34849,OPTSTK,ZEEL,29-Oct-2020,210.0,PE,0.00,0.00,0.00,75.05,61.95,0,0.00,0,0,10-AUG-2020,NaN

In [3]:
df.shape # Tells the Number of Rows and Columns present in the whole CSV File

(34850, 16)

In [4]:
df1 = df[df['INSTRUMENT'].str.contains('OPTIDX')] #Filtering only OPT from the whole Instruments
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
417,OPTIDX,BANKNIFTY,13-Aug-2020,16900.0,CE,5200.7,5200.7,5038.35,5038.35,5006.15,2,11.0,0,0,10-AUG-2020,NaN
418,OPTIDX,BANKNIFTY,13-Aug-2020,17000.0,CE,0.0,0.0,0.00,3432.50,4906.20,0,0.0,0,0,10-AUG-2020,NaN
419,OPTIDX,BANKNIFTY,13-Aug-2020,17100.0,CE,0.0,0.0,0.00,3356.00,4806.20,0,0.0,0,0,10-AUG-2020,NaN
420,OPTIDX,BANKNIFTY,13-Aug-2020,17200.0,CE,0.0,0.0,0.00,3280.45,4706.25,0,0.0,0,0,10-AUG-2020,NaN
421,OPTIDX,BANKNIFTY,13-Aug-2020,17300.0,CE,0.0,0.0,0.00,3205.80,4606.30,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.00,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.00,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.00,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.00,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.00,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [5]:
# Define all the symbols that you want the OPTINX and OPTSTK for in the multisymbols, in the same format
#Filtering all the symbols to a new dataframe
multisymbols = ['NIFTY']
df1 = df1[df['SYMBOL'].isin(multisymbols)]
df1

<ipython-input-5-f921a6e793f3>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['SYMBOL'].isin(multisymbols)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2039,OPTIDX,NIFTY,13-Aug-2020,8300.0,CE,0.0,0.0,0.0,1654.05,2973.05,0,0.0,0,0,10-AUG-2020,NaN
2040,OPTIDX,NIFTY,13-Aug-2020,8350.0,CE,0.0,0.0,0.0,1611.25,2923.05,0,0.0,0,0,10-AUG-2020,NaN
2041,OPTIDX,NIFTY,13-Aug-2020,8400.0,CE,0.0,0.0,0.0,1660.85,2873.10,0,0.0,0,0,10-AUG-2020,NaN
2042,OPTIDX,NIFTY,13-Aug-2020,8450.0,CE,0.0,0.0,0.0,1618.75,2823.10,0,0.0,0,0,10-AUG-2020,NaN
2043,OPTIDX,NIFTY,13-Aug-2020,8500.0,CE,0.0,0.0,0.0,1577.05,2773.10,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.0,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.0,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.0,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.0,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.0,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [6]:
#Change according to liking
#Get a single date or a specific date
dates = ["27-Aug-2020"] 
df1 = df1[df['EXPIRY_DT'].isin(dates)]
df1

<ipython-input-6-6674059c3095>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['EXPIRY_DT'].isin(dates)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2391,OPTIDX,NIFTY,27-Aug-2020,8000.0,CE,3293.95,3329.05,3261.30,3289.85,3289.85,313,2653.33,212475,-20100,10-AUG-2020,NaN
2392,OPTIDX,NIFTY,27-Aug-2020,8050.0,CE,0.00,0.00,0.00,1833.90,3236.05,0,0.00,0,0,10-AUG-2020,NaN
2393,OPTIDX,NIFTY,27-Aug-2020,8100.0,CE,0.00,0.00,0.00,1798.30,3186.15,0,0.00,0,0,10-AUG-2020,NaN
2394,OPTIDX,NIFTY,27-Aug-2020,8150.0,CE,0.00,0.00,0.00,1763.15,3136.25,0,0.00,0,0,10-AUG-2020,NaN
2395,OPTIDX,NIFTY,27-Aug-2020,8200.0,CE,0.00,0.00,0.00,1728.40,3086.35,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,OPTIDX,NIFTY,27-Aug-2020,12600.0,PE,1336.35,1336.35,1336.35,1336.35,1316.90,1,10.45,3300,75,10-AUG-2020,NaN
2581,OPTIDX,NIFTY,27-Aug-2020,12650.0,PE,0.00,0.00,0.00,1524.40,1365.10,0,0.00,0,0,10-AUG-2020,NaN
2582,OPTIDX,NIFTY,27-Aug-2020,12700.0,PE,1386.60,1430.60,1386.60,1430.60,1413.50,3,31.73,10500,-225,10-AUG-2020,NaN
2583,OPTIDX,NIFTY,27-Aug-2020,12750.0,PE,0.00,0.00,0.00,1476.55,1462.10,0,0.00,0,0,10-AUG-2020,NaN
2584,OPTIDX,NIFTY,27-Aug-2020,12800.0,PE,1507.00,1507.00,1472.45,1499.95,1499.95,11,117.84,8775,450,10-AUG-2020,NaN

In [7]:
#Filters out all the Values of only PE
df1 = df1[df['OPTION_TYP'].str.contains("PE")]
df1

<ipython-input-7-2e1b86d2d782>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1 = df1[df['OPTION_TYP'].str.contains("PE")]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2488,OPTIDX,NIFTY,27-Aug-2020,8000.0,PE,2.40,2.50,2.05,2.15,2.15,1947,11685.36,738075,-21075,10-AUG-2020,NaN
2489,OPTIDX,NIFTY,27-Aug-2020,8050.0,PE,0.00,0.00,0.00,296.05,0.05,0,0.00,0,0,10-AUG-2020,NaN
2490,OPTIDX,NIFTY,27-Aug-2020,8100.0,PE,2.45,2.70,2.20,2.30,2.30,158,960.14,23100,2700,10-AUG-2020,NaN
2491,OPTIDX,NIFTY,27-Aug-2020,8150.0,PE,0.00,0.00,0.00,324.10,0.05,0,0.00,0,0,10-AUG-2020,NaN
2492,OPTIDX,NIFTY,27-Aug-2020,8200.0,PE,2.10,2.80,2.05,2.40,2.40,61,375.26,14925,-150,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,OPTIDX,NIFTY,27-Aug-2020,12600.0,PE,1336.35,1336.35,1336.35,1336.35,1316.90,1,10.45,3300,75,10-AUG-2020,NaN
2581,OPTIDX,NIFTY,27-Aug-2020,12650.0,PE,0.00,0.00,0.00,1524.40,1365.10,0,0.00,0,0,10-AUG-2020,NaN
2582,OPTIDX,NIFTY,27-Aug-2020,12700.0,PE,1386.60,1430.60,1386.60,1430.60,1413.50,3,31.73,10500,-225,10-AUG-2020,NaN
2583,OPTIDX,NIFTY,27-Aug-2020,12750.0,PE,0.00,0.00,0.00,1476.55,1462.10,0,0.00,0,0,10-AUG-2020,NaN
2584,OPTIDX,NIFTY,27-Aug-2020,12800.0,PE,1507.00,1507.00,1472.45,1499.95,1499.95,11,117.84,8775,450,10-AUG-2020,NaN

In [8]:
df1 = df1.sort_values(['CHG_IN_OI'], ascending=False)
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2554,OPTIDX,NIFTY,27-Aug-2020,11300.0,PE,215.55,223.10,179.00,192.05,192.05,30526,263130.83,639450,191625,10-AUG-2020,NaN
2552,OPTIDX,NIFTY,27-Aug-2020,11200.0,PE,150.00,176.25,140.20,149.70,149.70,28751,244780.69,1368600,105525,10-AUG-2020,NaN
2546,OPTIDX,NIFTY,27-Aug-2020,10900.0,PE,63.05,78.75,62.00,66.65,66.65,17800,146423.15,961725,76875,10-AUG-2020,NaN
2543,OPTIDX,NIFTY,27-Aug-2020,10750.0,PE,46.65,52.85,40.30,42.85,42.85,1655,13398.92,73350,28650,10-AUG-2020,NaN
2551,OPTIDX,NIFTY,27-Aug-2020,11150.0,PE,140.05,153.75,124.05,131.30,131.30,1414,11965.32,56325,23550,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548,OPTIDX,NIFTY,27-Aug-2020,11000.0,PE,104.50,105.10,82.50,88.30,88.30,47960,398922.20,2991225,-71850,10-AUG-2020,NaN
2542,OPTIDX,NIFTY,27-Aug-2020,10700.0,PE,42.50,46.45,34.70,37.05,37.05,12527,100893.77,1015950,-75750,10-AUG-2020,NaN
2550,OPTIDX,NIFTY,27-Aug-2020,11100.0,PE,138.85,138.95,108.55,115.85,115.85,24818,208811.13,1215300,-79800,10-AUG-2020,NaN
2532,OPTIDX,NIFTY,27-Aug-2020,10200.0,PE,10.55,13.35,9.45,9.75,9.75,6984,53483.35,729600,-87450,10-AUG-2020,NaN
2568,OPTIDX,NIFTY,27-Aug-2020,12000.0,PE,733.00,760.50,681.55,720.95,720.95,4094,39011.39,435600,-124575,10-AUG-2020,NaN

In [9]:
df1 = df1.iloc[:1]
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
2554,OPTIDX,NIFTY,27-Aug-2020,11300.0,PE,215.55,223.1,179.0,192.05,192.05,30526,263130.83,639450,191625,10-AUG-2020,NaN

In [10]:
df1.to_csv('OPTIDX_PE_Nifty.csv')

In [11]:
DF = pd.read_csv("bhavdata.csv")
DF

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.10,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.00,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
3,FUTIDX,NIFTY,27-Aug-2020,0.0,XX,11274.95,11334.75,11242.05,11293.35,11293.35,125516,1063750.23,10313625,-35325,10-AUG-2020,NaN
4,FUTIDX,NIFTY,24-Sep-2020,0.0,XX,11262.00,11339.10,11252.95,11301.45,11301.45,6244,52947.72,948825,32175,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34845,OPTSTK,ZEEL,29-Oct-2020,190.0,PE,0.00,0.00,0.00,58.40,45.40,0,0.00,0,0,10-AUG-2020,NaN
34846,OPTSTK,ZEEL,29-Oct-2020,195.0,PE,0.00,0.00,0.00,62.45,49.40,0,0.00,0,0,10-AUG-2020,NaN
34847,OPTSTK,ZEEL,29-Oct-2020,200.0,PE,0.00,0.00,0.00,66.60,53.50,0,0.00,0,0,10-AUG-2020,NaN
34848,OPTSTK,ZEEL,29-Oct-2020,205.0,PE,0.00,0.00,0.00,70.80,57.70,0,0.00,0,0,10-AUG-2020,NaN
34849,OPTSTK,ZEEL,29-Oct-2020,210.0,PE,0.00,0.00,0.00,75.05,61.95,0,0.00,0,0,10-AUG-2020,NaN

In [12]:
df2 = DF[df['INSTRUMENT'].str.contains('OPTIDX')]
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
417,OPTIDX,BANKNIFTY,13-Aug-2020,16900.0,CE,5200.7,5200.7,5038.35,5038.35,5006.15,2,11.0,0,0,10-AUG-2020,NaN
418,OPTIDX,BANKNIFTY,13-Aug-2020,17000.0,CE,0.0,0.0,0.00,3432.50,4906.20,0,0.0,0,0,10-AUG-2020,NaN
419,OPTIDX,BANKNIFTY,13-Aug-2020,17100.0,CE,0.0,0.0,0.00,3356.00,4806.20,0,0.0,0,0,10-AUG-2020,NaN
420,OPTIDX,BANKNIFTY,13-Aug-2020,17200.0,CE,0.0,0.0,0.00,3280.45,4706.25,0,0.0,0,0,10-AUG-2020,NaN
421,OPTIDX,BANKNIFTY,13-Aug-2020,17300.0,CE,0.0,0.0,0.00,3205.80,4606.30,0,0.0,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,OPTIDX,NIFTY,26-Jun-2025,12000.0,PE,0.0,0.0,0.00,2743.10,1945.35,0,0.0,0,0,10-AUG-2020,NaN
4176,OPTIDX,NIFTY,26-Jun-2025,12500.0,PE,0.0,0.0,0.00,2992.55,2168.95,0,0.0,0,0,10-AUG-2020,NaN
4177,OPTIDX,NIFTY,26-Jun-2025,13000.0,PE,0.0,0.0,0.00,3249.25,2402.55,0,0.0,0,0,10-AUG-2020,NaN
4178,OPTIDX,NIFTY,26-Jun-2025,13500.0,PE,0.0,0.0,0.00,3294.80,2645.65,0,0.0,0,0,10-AUG-2020,NaN
4179,OPTIDX,NIFTY,26-Jun-2025,14000.0,PE,0.0,0.0,0.00,3300.50,2897.75,0,0.0,0,0,10-AUG-2020,NaN

In [13]:
multsym = ['BANKNIFTY']
df2 = DF[df['SYMBOL'].isin(multsym)]
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.0,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
1,FUTIDX,BANKNIFTY,24-Sep-2020,0.0,XX,21888.75,22093.1,21807.00,21955.30,21955.30,4557,25044.39,67150,2375,10-AUG-2020,NaN
2,FUTIDX,BANKNIFTY,29-Oct-2020,0.0,XX,21899.95,22100.0,21784.85,21974.10,21974.10,292,1605.30,7750,550,10-AUG-2020,NaN
417,OPTIDX,BANKNIFTY,13-Aug-2020,16900.0,CE,5200.70,5200.7,5038.35,5038.35,5006.15,2,11.00,0,0,10-AUG-2020,NaN
418,OPTIDX,BANKNIFTY,13-Aug-2020,17000.0,CE,0.00,0.0,0.00,3432.50,4906.20,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034,OPTIDX,BANKNIFTY,29-Oct-2020,24400.0,PE,0.00,0.0,0.00,3587.00,3051.40,0,0.00,0,0,10-AUG-2020,NaN
2035,OPTIDX,BANKNIFTY,29-Oct-2020,24500.0,PE,0.00,0.0,0.00,3658.40,3124.70,0,0.00,0,0,10-AUG-2020,NaN
2036,OPTIDX,BANKNIFTY,29-Oct-2020,24600.0,PE,0.00,0.0,0.00,3730.35,3198.75,0,0.00,0,0,10-AUG-2020,NaN
2037,OPTIDX,BANKNIFTY,29-Oct-2020,24700.0,PE,0.00,0.0,0.00,3636.65,3273.45,0,0.00,0,0,10-AUG-2020,NaN
2038,OPTIDX,BANKNIFTY,29-Oct-2020,24800.0,PE,0.00,0.0,0.00,3710.20,3348.90,0,0.00,0,0,10-AUG-2020,NaN

In [14]:
df2 = df2[df['EXPIRY_DT'].isin(dates)]
df2

<ipython-input-14-9aa28cb238d1>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df['EXPIRY_DT'].isin(dates)]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
0,FUTIDX,BANKNIFTY,27-Aug-2020,0.0,XX,21851.00,22099.00,21802.00,21956.35,21956.35,217030,1192952.77,1310550,-26050,10-AUG-2020,NaN
767,OPTIDX,BANKNIFTY,27-Aug-2020,16200.0,CE,0.00,0.00,0.00,5200.00,5732.35,0,0.00,25,0,10-AUG-2020,NaN
768,OPTIDX,BANKNIFTY,27-Aug-2020,16300.0,CE,0.00,0.00,0.00,4431.95,5632.55,0,0.00,0,0,10-AUG-2020,NaN
769,OPTIDX,BANKNIFTY,27-Aug-2020,16400.0,CE,0.00,0.00,0.00,4372.10,5532.80,0,0.00,0,0,10-AUG-2020,NaN
770,OPTIDX,BANKNIFTY,27-Aug-2020,16500.0,CE,5475.15,5580.60,5427.60,5427.60,5433.00,37,203.72,2925,-350,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,OPTIDX,BANKNIFTY,27-Aug-2020,25700.0,PE,0.00,0.00,0.00,3315.45,3772.35,0,0.00,0,0,10-AUG-2020,NaN
963,OPTIDX,BANKNIFTY,27-Aug-2020,25800.0,PE,0.00,0.00,0.00,3391.55,3869.55,0,0.00,0,0,10-AUG-2020,NaN
964,OPTIDX,BANKNIFTY,27-Aug-2020,25900.0,PE,0.00,0.00,0.00,3468.35,3967.00,0,0.00,0,0,10-AUG-2020,NaN
965,OPTIDX,BANKNIFTY,27-Aug-2020,26000.0,PE,4020.00,4069.85,3954.25,4069.85,4064.70,12,89.97,4500,-300,10-AUG-2020,NaN
966,OPTIDX,BANKNIFTY,27-Aug-2020,26100.0,PE,0.00,0.00,0.00,3318.65,4162.65,0,0.00,0,0,10-AUG-2020,NaN

In [15]:
#Filters out all the Values of only PE
df2 = df2[df['OPTION_TYP'].str.contains('PE')]
df2

<ipython-input-15-1b4c1a32c268>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df['OPTION_TYP'].str.contains('PE')]

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
867,OPTIDX,BANKNIFTY,27-Aug-2020,16200.0,PE,8.95,9.50,8.50,9.30,9.30,87,352.54,7900,25,10-AUG-2020,NaN
868,OPTIDX,BANKNIFTY,27-Aug-2020,16300.0,PE,0.00,0.00,0.00,1364.25,0.10,0,0.00,0,0,10-AUG-2020,NaN
869,OPTIDX,BANKNIFTY,27-Aug-2020,16400.0,PE,0.00,0.00,0.00,1403.15,0.10,0,0.00,0,0,10-AUG-2020,NaN
870,OPTIDX,BANKNIFTY,27-Aug-2020,16500.0,PE,8.10,10.50,8.05,9.45,9.45,374,1543.61,9175,-1100,10-AUG-2020,NaN
871,OPTIDX,BANKNIFTY,27-Aug-2020,16600.0,PE,0.00,0.00,0.00,1482.85,0.20,0,0.00,0,0,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,OPTIDX,BANKNIFTY,27-Aug-2020,25700.0,PE,0.00,0.00,0.00,3315.45,3772.35,0,0.00,0,0,10-AUG-2020,NaN
963,OPTIDX,BANKNIFTY,27-Aug-2020,25800.0,PE,0.00,0.00,0.00,3391.55,3869.55,0,0.00,0,0,10-AUG-2020,NaN
964,OPTIDX,BANKNIFTY,27-Aug-2020,25900.0,PE,0.00,0.00,0.00,3468.35,3967.00,0,0.00,0,0,10-AUG-2020,NaN
965,OPTIDX,BANKNIFTY,27-Aug-2020,26000.0,PE,4020.00,4069.85,3954.25,4069.85,4064.70,12,89.97,4500,-300,10-AUG-2020,NaN
966,OPTIDX,BANKNIFTY,27-Aug-2020,26100.0,PE,0.00,0.00,0.00,3318.65,4162.65,0,0.00,0,0,10-AUG-2020,NaN

In [16]:
df2 = df2.sort_values(['CHG_IN_OI'], ascending=False)
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
900,OPTIDX,BANKNIFTY,27-Aug-2020,19500.0,PE,58.05,58.05,42.55,45.80,45.80,6376,31159.36,132550,32300,10-AUG-2020,NaN
905,OPTIDX,BANKNIFTY,27-Aug-2020,20000.0,PE,103.95,104.00,76.65,85.15,85.15,16417,82434.23,351250,28300,10-AUG-2020,NaN
925,OPTIDX,BANKNIFTY,27-Aug-2020,22000.0,PE,690.00,718.00,579.60,635.60,635.60,12339,69791.00,135550,12900,10-AUG-2020,NaN
930,OPTIDX,BANKNIFTY,27-Aug-2020,22500.0,PE,936.95,1028.80,850.10,917.65,917.65,2166,12675.82,63300,8100,10-AUG-2020,NaN
915,OPTIDX,BANKNIFTY,27-Aug-2020,21000.0,PE,300.70,302.10,231.40,256.40,256.40,17256,91695.99,210425,6975,10-AUG-2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,OPTIDX,BANKNIFTY,27-Aug-2020,18000.0,PE,15.00,15.00,9.85,10.85,10.85,910,4097.50,97875,-2650,10-AUG-2020,NaN
890,OPTIDX,BANKNIFTY,27-Aug-2020,18500.0,PE,18.45,18.45,13.25,14.95,14.95,1419,6568.38,74650,-2825,10-AUG-2020,NaN
910,OPTIDX,BANKNIFTY,27-Aug-2020,20500.0,PE,189.50,189.50,136.80,152.55,152.55,12123,62588.51,147150,-3825,10-AUG-2020,NaN
920,OPTIDX,BANKNIFTY,27-Aug-2020,21500.0,PE,465.45,477.50,378.25,415.95,415.95,17219,94314.53,201175,-19800,10-AUG-2020,NaN
895,OPTIDX,BANKNIFTY,27-Aug-2020,19000.0,PE,32.15,34.20,23.15,25.25,25.25,5855,27850.37,168175,-37575,10-AUG-2020,NaN

In [17]:
df2 = df2.iloc[:1]
df2

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,CLOSE,SETTLE_PR,CONTRACTS,VAL_INLAKH,OPEN_INT,CHG_IN_OI,TIMESTAMP,Unnamed: 15
900,OPTIDX,BANKNIFTY,27-Aug-2020,19500.0,PE,58.05,58.05,42.55,45.8,45.8,6376,31159.36,132550,32300,10-AUG-2020,NaN

In [18]:
df2.to_csv('OPTIDX_PE_Banknifty.csv')